### ISSUE TITLE
What about Dynamic Page Title & Meta Info?

### ISSUE THREAD

**Issue by AhsanAbrar** [codecasts/spa-starter-kit#102]
no doubt it's great effort from your side.

but i searched lot on internet but can't find any proper solution for Routes Page Title & Meta info.

you should add this feature too in your repo.

it'll help me lot & others too :)

**Comment by vedovelli** [comment]
Thank you for your suggestion!

Despite being a good one, it is out of the scope of this project. 

Best regards,

Vedovelli

**Comment by hernandev** [comment]
@vedovelli, @vinicius73's seo-tools solves this

**Comment by AhsanAbrar** [comment]
this is for Laravel not suitable for single page app.

how we can use this with index.html ?
page title and meta info issue should be solved in single page app.
