### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by wit3** [codecasts/spa-starter-kit#107]
Hi.. 
I've been found a bug.
After about 60 minutes without making a request to the server, if you try to press any button (ex: edit categories) that executes a request, you will have a redirect with the following error message.

Good new year at all :)
![fireshot capture 008 - codecasts com br - spa - starter k_ - https___spa codecasts rocks_auth_singin](https://cloud.githubusercontent.com/assets/5450259/21589973/a95604c8-d0f7-11e6-98f6-5293b561d36b.png)

This is the json response message:

`{"messages":["Token has expired"],"reason":"token_expired","trace":[{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/tymon\/jwt-auth\/src\/Http\/Middleware\/Authenticate.php","line":30,"function":"authenticate","class":"Tymon\\JWTAuth\\Http\\Middleware\\BaseMiddleware","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9904,"function":"handle","class":"Tymon\\JWTAuth\\Http\\Middleware\\Authenticate","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php","line":33,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/barryvdh\/laravel-cors\/src\/HandleCors.php","line":42,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9904,"function":"handle","class":"Barryvdh\\Cors\\HandleCors","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php","line":33,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":10012,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9904,"function":"handle","class":"Illuminate\\Routing\\Middleware\\SubstituteBindings","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php","line":33,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/ThrottleRequests.php","line":49,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9904,"function":"handle","class":"Illuminate\\Routing\\Middleware\\ThrottleRequests","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{},"60","1"]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php","line":33,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9889,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":8191,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":8182,"function":"runRouteWithinStack","class":"Illuminate\\Routing\\Router","type":"->","args":[{},{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":8173,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":2471,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php","line":53,"function":"Illuminate\\Foundation\\Http\\{closure}","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/barryvdh\/laravel-cors\/src\/HandleCors.php","line":42,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9904,"function":"handle","class":"Barryvdh\\Cors\\HandleCors","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php","line":33,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":3226,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9904,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php","line":33,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":9889,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Pipeline","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":2415,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->","args":[{}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/bootstrap\/cache\/compiled.php","line":2399,"function":"sendRequestThroughRouter","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/vhosts\/spa.vedcasts.com.br\/httpdocs\/public\/index.php","line":53,"function":"handle","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]}]}`

**Comment by vinicius73** [comment]
Thanks @Wit3 
we have knowledge about this error #39 and #64

**Comment by wit3** [comment]
@vinicius73 Ok. thanks!
