### ISSUE TITLE
Prevents logged user

### ISSUE THREAD

**Issue by jaonoctus** [codecasts/spa-starter-kit#118]
Prevent the user from accessing the auth route like `/auth/signin` if logged in.

**Comment by jaonoctus** [comment]
@vedovelli we can do something like that on `router/beforeEach.js`:

```javascript

const preventsLogged = prevents => prevents === true
const prevents = to.meta.preventsLogged

if (isLogged && preventsLogged(prevents)) {
  return next({ name: 'dashboard.index' })
}
```

and add the meta on each auth route.
```javascript
preventsLogged: true
```

**Comment by vedovelli** [comment]
Hello @JaoNoctus ! 

Why not implement it yourself and send it in a pull request?! ;)
