### ISSUE TITLE
Migration to use Quasar

### ISSUE THREAD

**Issue by vinicius73** [codecasts/spa-starter-kit#120]
I have kind of a very good experience using Quasar, it is very ~~complex~~ complete and simple.

I would like to migrate our code to work with it, what do you think of the idea?

http://quasar-framework.org/

http://quasar-framework.org/quasar-play/android/index.html#/showcase

**Comment by vedovelli** [comment]
What do you mean by "it is very complex and simple" ? 

I vote for a separate project.

**Comment by vinicius73** [comment]
sorry @vedovelli 
complex => complete
typofix

**Comment by carvalhoviniciusluiz** [comment]
It could have a quasar-branch to exemplify if it is the case how it is used..

**Comment by vinicius73** [comment]
Good Idea @carvalhoviniciusluiz
I will do this
