### ISSUE TITLE
Should we migrate to Lumen?

### ISSUE THREAD

**Issue by flyingluscas** [codecasts/spa-starter-kit#121]
Hi guys,

I recently have started developing an API using Lumen, and in my experience has been quite simple and faster than using Laravel itself.

I think the reason is that Laravel is not meant for just APIs, so he brings a lot of things that we don't need when building an API, like session management, CSRF protection among other things.

So I was thinking if it is worth migrate to Lumen? because in my opinion, the API would be faster and the code would be more clean and simple.

What do you guys think?

**Comment by vinicius73** [comment]
I do not like Lumen.
It is designed for micro-services, nor is the whole API a micro-service.
There are several features that are very important in Laravel and are not simple to get in Lumen, apart from packages that are not always compatible.

On the other hand indifere what Vue is going to consume, so it makes no difference.

But I think if this happens it has to be on a separate project.

**Comment by vedovelli** [comment]
We should stick to Laravel. Same as @vinicius73 I don't like Lumen.

We can remove from Laravel everything not related to APIs, such as Blade, for instance.

Thanks for the suggestion!

Ved
