### ISSUE TITLE
Unable to get roles and permissions

### ISSUE THREAD

**Issue by whevether** [codecasts/spa-starter-kit#122]
How are you doing! I use Ultraware/Roles this permission pack. ``
`User::find(1)->getRoles();`
Gets the role to be empty, but the Laravel auth can fetch;

**Comment by vedovelli** [comment]
Hello! Thanks for opening the issue.

It is unrelated to this project so I'd advise you to open an issue in the Ultraware/Roles repository.

Have a nice day!
