### ISSUE TITLE
Error in demo and repository can not be accessed

### ISSUE THREAD

**Issue by dyagomatheus** [codecasts/spa-starter-kit#124]
I'm trying to access the demo, but it's not possible. Also I can not do the installation of the files, it returns me error saying to check if the repository is still available.

**Comment by cristiano-pacheco** [comment]
Hello @dyagomatheus,

@Vedovelli is checking the demo, as per issue #123 

Regarding the error that is occurring in the local installation, did you perform the procedure described in the project README installation session?

**Comment by dyagomatheus** [comment]
Hello @cristianopacheco,

I apologize, it was my mistake for not having git installed on my machine.
Now everything is perfect. Except for the demo.

**Comment by vinicius73** [comment]
@dyagomatheus
