### ISSUE TITLE
Integrate with Element

### ISSUE THREAD

**Issue by vinicius73** [codecasts/spa-starter-kit#13]
http://element.eleme.io/#/en-US

**Comment by vitorarjol** [comment]
Um repositório com um exemplo: https://github.com/taylorchen709/vueAdmin

**Comment by vedovelli** [comment]
This is a WIP.

**Comment by vedovelli** [comment]
For the version 1.0.3 only Navbar component is built on top of Element UI. In a very near future all components will benefit from it and then we're gonna ditch Bootstrap.

**Comment by vedovelli** [comment]
At the moment we also have Table and Pagination.

Next and final step will be adopting structural components (such as Grid) and then remove Bootstrap dependency for good.

Then this issue will be closed.
