### ISSUE TITLE
php.codecasts.rocks is down

### ISSUE THREAD

**Issue by lawrencedudley** [codecasts/spa-starter-kit#132]
<img width="939" alt="screen shot 2018-08-21 at 10 33 34" src="https://user-images.githubusercontent.com/272317/44393873-b4c94200-a52d-11e8-824a-ccbc0f84be89.png">

**Comment by lawrencedudley** [comment]
Sorted now!

**Comment by lionsdad** [comment]
Same issue again
![Screenshot 2019-05-28 14 21 51](https://user-images.githubusercontent.com/11161652/58474504-f7bae480-8153-11e9-93b7-1c5ecaef1d31.png)

**Comment by berserker5000** [comment]
any updates? site not working yet...

**Comment by lionsdad** [comment]
@berserker5000 its deprecated. Check this [link](https://github.com/codecasts/php-alpine/issues/78)
