### ISSUE TITLE
.gitignore, .gitattributes, and app.scss

### ISSUE THREAD

**Issue by 58bits** [codecasts/spa-starter-kit#31]
Great project! 

Would you consider adding .idea to the root .gitignore file?

Also I believe it's good practice to protect Web fonts from text encoding, by including the following in a .gitattributes file (so that fonts in /client/src/assets/fonts are treated as binary files).

```
*.ttf   binary
*.otf   binary
*.eot   binary
*.woff  binary
*.woff2 binary
```

Also I believe that `/client/src/assets/sass/app.scss` can be updated as below, with correct paths to node_modules for imports. I've tested this in dev and build environments and it compiles fine. I'd be happy to submit a pull request for both if you think this is okay.

```sass
// Fonts
@import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600);

// Variables
@import "variables";

// Bootstrap
@import "../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap";

// Font-awesome
@import "../../../node_modules/font-awesome/scss/font-awesome.scss";

// SweetAlert
@import "../../../node_modules/sweetalert/dev/sweetalert.scss";
```

**Comment by vedovelli** [comment]
Hello @58bits !

Thanks for your comments. Your pull requests are welcome!

Before doing so would you please clarify why using '../../../' is better than the current implementation? Please consider there's a third way of doing this by including a ~

'~node_modules/...'

Thanks a lot!

Vedovelli

**Comment by 58bits** [comment]
I'm using an IDEA based editor (PhpStorm) and '../../../' resolves correctly in the editor, as well as in the build process. It also means that the sass files will build correctly with tools other than Webpack (as an option). I also realize you can use '~node_modules/...', and that the editor warnings could be turned off, but I feel that having a node-sass buildable set of scss assets might be okay too - independent of whatever build tools are in use.

**Comment by vedovelli** [comment]
Thanks for the reply!

Please send you PR!
