### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by 58bits** [codecasts/spa-starter-kit#32]
Just a suggestion, but we've been building with Bootstrap 4 for a while now, and it's very stable - at Alpha 5 now.

Would you consider updating the starter kit to use Bootstrap 4?

`npm install bootstrap@4.0.0-alpha.5`

**Comment by vedovelli** [comment]
Thanks for your comment.

Actually we have plans to completely ditch Bootstrap in favour of Element.io

Regards,

Vedovelli

**Comment by vedovelli** [comment]
Thanks for your comment.

Actually we have plans to completely ditch Bootstrap in favour of Element.io

Regards,

Vedovelli

**Comment by 58bits** [comment]
I'm not familiar with element.io - can you include a link? (http://element.io/ points to a parked domain).

**Comment by vedovelli** [comment]
Sure!! http://element.eleme.io/#/en-US

**Comment by 58bits** [comment]
Thanks!
