### ISSUE TITLE
Why why why ?

### ISSUE THREAD

**Issue by Fatih90** [codecasts/spa-starter-kit#38]
why are you not using vue from https://github.com/codecasts/spa-starter-kit/tree/master/webservice/resources/assets/js ?

**Comment by hernandev** [comment]
This is a SPA application @Fatih90, there are two isolated projects here:

`webservice` and `client` folders. The JS files on the API side are not needed, they can be deleted by the way.

@vedovelli may be able to provide you some links so you can learn how a SPA application works.
