### ISSUE TITLE
Auth router implementation

### ISSUE THREAD

**Issue by Wit3** [codecasts/spa-starter-kit#42]
Hello .. it is not planned a more complex implementation authenticated route system?
This package is very powerful, can we expect to implement it in the future?

Vue Auth : https://github.com/websanova/vue-auth/
Thanks

**Comment by vedovelli** [comment]
@Wit3 

Thanks for the suggestion. It is the first time I read about Vue-auth. 

We will take a closer look and if is solid we will consider bringing it in the project.

This issue shall stay open until we finish our evaluation.

Best regards,

Vedovelli

**Comment by vedovelli** [comment]
@vinicius73, @cristianopacheco what do you guys think about it? Thanks!

**Comment by vinicius73** [comment]
this is interessante, but i am afraid to use a third party lib  in auth system.
auth systems are commonly the most complex part of the project, with lot of custom rules.

I prefer not use this lib now, maybe in the future

**Comment by vedovelli** [comment]
@vinicius73 I'm with you.

The original purpose of this project is to glue together the tools required to build SPAs with Vue.js and Laravel. So I tried to stick with the packages provided by the core team and only with those.

Let us get back to this subject after you finish the auth implementation. Thanks.

@Wit3 thanks for your suggestion but we are not going for it at the moment.
