### ISSUE TITLE
Problemas no cors da api laravel

### ISSUE THREAD

**Issue by mbrunogregorio** [codecasts/spa-starter-kit#7]
Baixei o projeto e tentei executar, mas não rola, dá erro na hora de enviar a requisição de login. Alguém mais com esse erro?
Olhem o anexo:
![ccast](https://cloud.githubusercontent.com/assets/5339480/20688035/cc94f43c-b59d-11e6-8679-fe2d862f7e09.png)

**Comment by vedovelli** [comment]
Qual o seu sistema operacional?

Você já rodou com sucesso algum web service com CORS neste ambiente antes?

Obrigado.

**Comment by mbrunogregorio** [comment]
Foi no windows. Já rodei cors nele sim, o esquisito é que eu consigo fazer a requisição http pelo Postman, mas quando é pelo "client" não vai, diz que tá faltando o header Access-Control-Allow-Origin.
:|

**Comment by vedovelli** [comment]
Pessoalmente já instalei com sucesso em 3 locais, mas nenhum deles windows.

Estes são os arquivos chave no CORS. Verifique se vc os tem na sua instalação local.

https://github.com/codecasts/spa-starter-kit/blob/master/webservice/config/cors.php

https://github.com/codecasts/spa-starter-kit/blob/master/webservice/routes/api.php#L5

https://github.com/codecasts/spa-starter-kit/blob/master/webservice/app/Http/Kernel.php#L55-L56

**Comment by mbrunogregorio** [comment]
Sim, tudo certinho com esses 3 arquivos, pelo jeito o problema está no header da requisição feita pelo client.
Obrigado pela atenção. o//

**Comment by vedovelli** [comment]
Qual o seu webserver? Será que o webserver não está impedindo que os headers que habilitam CORS sejam enviados com a resposta?

Apenas divagando aqui...

**Comment by mbrunogregorio** [comment]
Eu to fazendo tudo exatamente como no exemplo, unica coisa que está diferente é o php5.6. Será que pode ser isso?
