### ISSUE TITLE
[client] Page loader

### ISSUE THREAD

**Issue by vinicius73** [codecasts/spa-starter-kit#70]
- Page loader for navigation
- Manual trigger

**Comment by vedovelli** [comment]
@vinicius73 What is it about?! Do you have any example?!

**Comment by vinicius73** [comment]
Loaders like http://simbyone.com/demo/30-css-page-preload-animations/
But, element have a full-loader, is useful and simple

**Comment by oteroweb** [comment]
You can use v-cloak on the component: http://vuejs.org/api/#v-cloak
