### ISSUE TITLE
JavaScript Style

### ISSUE THREAD

**Issue by 58bits** [codecasts/spa-starter-kit#74]
Curious to know why the project isn't using the 'standard' eslint settings. There are  Webpack options for linting that come ready to go with the Vuejs.org Webpack template starter (on which this project is based)...

https://github.com/vuejs-templates/webpack 
https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style

Dangling commas in particular are a PHP PSR recommendation I believe, but not usually found in JavaScript.

No strong feelings here, but curious nevertheless. ;-)

**Comment by vinicius73** [comment]
The best person to answer this is @vedovelli 
I currently prefer JavaScript Standard

**Comment by vedovelli** [comment]
Personal preference and nothing else! =D

**Comment by 58bits** [comment]
Okay - well just a thought - but if you're aiming this as a starter kit, for others to use, then you might consider changing to the default linter and coding style that comes with the Vuejs.org Webpack template, otherwise it's a fairly big task for anyone to update the coding style to match (they'll have to manually edit the JS to and 'fix it up to' get the linter to pass for Webpack builds).
