### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by 58bits** [codecasts/spa-starter-kit#84]
I think the following (and elsewhere) in https://github.com/codecasts/spa-starter-kit/blob/develop/client/src/components/general/pagination.vue#L33

```
isLast() {
        return this.currentPage === this.paginationData.last_page
}
```

should be...

```
isLast() {
        return this.currentPage === this.paginationData.total_pages
}
```

I don't see a `last_page` property in the meta section of the response for products. Here's a gist to the output...

https://gist.github.com/58bits/833dbb582fedd0e0345189776049bce4

**Comment by vedovelli** [comment]
Thanks @58bits 

I'll fix this!
