### ISSUE TITLE
GET request preflight OPTIONS - CORS

### ISSUE THREAD

**Issue by wit3** [codecasts/spa-starter-kit#87]
Hi guys.

Why do you use preflight option  in simple get request? 

Example : https://spa.codecasts.rocks/categories?page=9

**Comment by vedovelli** [comment]
Hey @Wit3 !

I assume this is default for the browser. If a preflight is necessary for POST or PUT why not for GET?

If not the browser then Axios.

If you have more details on this matter just add to the issue! Thanks!

Vedovelli

**Comment by karneaud** [comment]
I'm using your project and I'm getting a 301 error on one go my api endpoints I'm using your standard setup with the jet, api and auth middlewares on a Route::resource but it doesn't seem to play well......any suggestions?
