### ISSUE TITLE
Fractal error while navigating in the Product list

### ISSUE THREAD

**Issue by vedovelli** [codecasts/spa-starter-kit#89]
`Type error: Argument 1 passed to App\Transformers\CategoryTransformer::transform() must be an instance of App\Category, null given, called in /Users/vedovelli/Codecasts/spa-starter-kit/webservice/vendor/league/fractal/src/Scope.php on line 365`

This is the message coming from the server.

Could you please take a look? Thanks!

**Comment by vedovelli** [comment]
![screen shot 2016-12-20 at 18 52 03](https://cloud.githubusercontent.com/assets/151001/21367474/6f92797c-c6e5-11e6-80cc-aaf2484014e2.png)

**Comment by flyingluscas** [comment]
@vedovelli I'll fix this
