### ISSUE TITLE
Bug on demo page

### ISSUE THREAD

**Issue by IgorDePaula** [codecasts/spa-starter-kit#93]
![bugspastarterkit](https://cloud.githubusercontent.com/assets/2833993/21397707/f7e139de-c78b-11e6-9858-16073b019963.png)

**Comment by vedovelli** [comment]
Thanks for reporting. This is currently fixed in our develop branch.

Demo shall be updated later today.

**Comment by vedovelli** [comment]
@IgorDePaula Demo is updated to the new dev version. Do you mind checking it out again? Thanks!

**Comment by IgorDePaula** [comment]
@vedovelli Now is OK, Thanks by attention.
